// <auto-generated />
using System;
using InTicket.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InTicket.Persistence.Migrations
{
    [DbContext(typeof(InTicketDbContext))]
    partial class InTicketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InTicket.Domain.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmailConfirmationOtp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailConfirmationOtpExpiration")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid?>("FavoriteTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InTicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastOtpAttemptAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("OtpAttempts")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetOtp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetOtpExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("FavoriteTeamId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("InTicket.Domain.BaseEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BaseEvents");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("InTicket.Domain.Delegation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DelegateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DelegateNationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DelegatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DelegateId");

                    b.HasIndex("DelegatorId")
                        .IsUnique();

                    b.ToTable("Delegations", (string)null);
                });

            modelBuilder.Entity("InTicket.Domain.Payments", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Done")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("TicketIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PaymentId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("InTicket.Domain.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FoundedYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            City = "Manchester",
                            FoundedYear = 1880,
                            Name = "Manchester City",
                            Stadium = "Etihad Stadium"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            City = "London",
                            FoundedYear = 1886,
                            Name = "Arsenal",
                            Stadium = "Emirates Stadium"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            City = "Liverpool",
                            FoundedYear = 1892,
                            Name = "Liverpool",
                            Stadium = "Anfield"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            City = "Manchester",
                            FoundedYear = 1878,
                            Name = "Manchester United",
                            Stadium = "Old Trafford"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            City = "London",
                            FoundedYear = 1905,
                            Name = "Chelsea",
                            Stadium = "Stamford Bridge"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            City = "London",
                            FoundedYear = 1882,
                            Name = "Tottenham Hotspur",
                            Stadium = "Tottenham Hotspur Stadium"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            City = "Newcastle upon Tyne",
                            FoundedYear = 1892,
                            Name = "Newcastle United",
                            Stadium = "St James' Park"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            City = "Birmingham",
                            FoundedYear = 1874,
                            Name = "Aston Villa",
                            Stadium = "Villa Park"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            City = "Brighton",
                            FoundedYear = 1901,
                            Name = "Brighton & Hove Albion",
                            Stadium = "Amex Stadium"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            City = "London",
                            FoundedYear = 1895,
                            Name = "West Ham United",
                            Stadium = "London Stadium"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            City = "Wolverhampton",
                            FoundedYear = 1877,
                            Name = "Wolverhampton Wanderers",
                            Stadium = "Molineux Stadium"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            City = "Liverpool",
                            FoundedYear = 1878,
                            Name = "Everton",
                            Stadium = "Goodison Park"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            City = "London",
                            FoundedYear = 1889,
                            Name = "Brentford",
                            Stadium = "Gtech Community Stadium"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            City = "London",
                            FoundedYear = 1879,
                            Name = "Fulham",
                            Stadium = "Craven Cottage"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            City = "London",
                            FoundedYear = 1905,
                            Name = "Crystal Palace",
                            Stadium = "Selhurst Park"
                        },
                        new
                        {
                            Id = new Guid("12121212-1212-1212-1212-121212121212"),
                            City = "Nottingham",
                            FoundedYear = 1865,
                            Name = "Nottingham Forest",
                            Stadium = "City Ground"
                        },
                        new
                        {
                            Id = new Guid("34343434-3434-3434-3434-343434343434"),
                            City = "Bournemouth",
                            FoundedYear = 1899,
                            Name = "Bournemouth",
                            Stadium = "Vitality Stadium"
                        },
                        new
                        {
                            Id = new Guid("56565656-5656-5656-5656-565656565656"),
                            City = "Sheffield",
                            FoundedYear = 1889,
                            Name = "Sheffield United",
                            Stadium = "Bramall Lane"
                        },
                        new
                        {
                            Id = new Guid("78787878-7878-7878-7878-787878787878"),
                            City = "Burnley",
                            FoundedYear = 1882,
                            Name = "Burnley",
                            Stadium = "Turf Moor"
                        },
                        new
                        {
                            Id = new Guid("90909090-9090-9090-9090-909090909090"),
                            City = "Luton",
                            FoundedYear = 1885,
                            Name = "Luton Town",
                            Stadium = "Kenilworth Road"
                        });
                });

            modelBuilder.Entity("InTicket.Domain.Ticket", b =>
                {
                    b.Property<Guid>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BookedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HeldAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HeldExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HolderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("TicketId");

                    b.HasIndex("HolderId");

                    b.ToTable("Tickets");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("InTicket.Domain.Concert", b =>
                {
                    b.HasBaseType("InTicket.Domain.BaseEvent");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BookingStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("MinimumAge")
                        .HasColumnType("int");

                    b.Property<string>("Organizer")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Concerts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000001"),
                            Description = "Coldplay live in an unforgettable night of music",
                            EventDate = new DateTime(2025, 3, 15, 19, 30, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            Location = "",
                            Title = "Coldplay: Music of the Spheres Tour",
                            Venue = "Wembley Stadium",
                            Artist = "Coldplay",
                            BookingStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationMinutes = 130,
                            MinimumAge = 12,
                            Organizer = "Live Nation"
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000002"),
                            Description = "A soulful evening with Adele",
                            EventDate = new DateTime(2025, 4, 10, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            Location = "",
                            Title = "Adele Live in London",
                            Venue = "The O2 Arena",
                            Artist = "Adele",
                            BookingStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationMinutes = 120,
                            MinimumAge = 10,
                            Organizer = "AEG Presents"
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000003"),
                            Description = "Ed Sheeran performing his greatest hits",
                            EventDate = new DateTime(2025, 5, 5, 19, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            Location = "",
                            Title = "Ed Sheeran Mathematics Tour",
                            Venue = "Etihad Stadium",
                            Artist = "Ed Sheeran",
                            BookingStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationMinutes = 135,
                            MinimumAge = 8,
                            Organizer = "Kilimanjaro Live"
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000004"),
                            Description = "High-energy performance by Imagine Dragons",
                            EventDate = new DateTime(2025, 6, 20, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            Location = "",
                            Title = "Imagine Dragons World Tour",
                            Venue = "Tottenham Hotspur Stadium",
                            Artist = "Imagine Dragons",
                            BookingStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationMinutes = 125,
                            MinimumAge = 10,
                            Organizer = "SJM Concerts"
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000005"),
                            Description = "An orchestral experience of movie soundtracks",
                            EventDate = new DateTime(2025, 7, 12, 19, 30, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            Location = "",
                            Title = "Hans Zimmer Live",
                            Venue = "Royal Albert Hall",
                            Artist = "Hans Zimmer",
                            BookingStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationMinutes = 150,
                            MinimumAge = 12,
                            Organizer = "Semmel Concerts"
                        });
                });

            modelBuilder.Entity("InTicket.Domain.Match", b =>
                {
                    b.HasBaseType("InTicket.Domain.BaseEvent");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FanPriorityBookingStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GeneralBookingStart")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("League")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Round")
                        .HasColumnType("int");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StadiumCapacity")
                        .HasColumnType("int");

                    b.Property<string>("StadiumName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("Matches", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Description = "Premier League clash between title contenders",
                            EventDate = new DateTime(2025, 12, 28, 18, 30, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            Location = "",
                            Title = "Manchester City vs Arsenal",
                            Venue = "Etihad Stadium",
                            AwayTeamId = new Guid("22222222-2222-2222-2222-222222222222"),
                            FanPriorityBookingStart = new DateTime(2025, 12, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            GeneralBookingStart = new DateTime(2025, 12, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            HomeTeamId = new Guid("11111111-1111-1111-1111-111111111111"),
                            League = "Premier League",
                            Round = 18,
                            Season = "2025/2026",
                            StadiumCapacity = 0,
                            StadiumName = "Etihad Stadium"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000002"),
                            Description = "Historic rivalry at Anfield",
                            EventDate = new DateTime(2025, 12, 29, 16, 30, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            Location = "",
                            Title = "Liverpool vs Manchester United",
                            Venue = "Anfield",
                            AwayTeamId = new Guid("44444444-4444-4444-4444-444444444444"),
                            FanPriorityBookingStart = new DateTime(2025, 12, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            GeneralBookingStart = new DateTime(2025, 12, 7, 10, 0, 0, 0, DateTimeKind.Utc),
                            HomeTeamId = new Guid("33333333-3333-3333-3333-333333333333"),
                            League = "Premier League",
                            Round = 19,
                            Season = "2025/2026",
                            StadiumCapacity = 0,
                            StadiumName = "Anfield"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000003"),
                            Description = "London derby",
                            EventDate = new DateTime(2025, 12, 30, 17, 30, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            Location = "",
                            Title = "Chelsea vs Tottenham Hotspur",
                            Venue = "Stamford Bridge",
                            AwayTeamId = new Guid("66666666-6666-6666-6666-666666666666"),
                            FanPriorityBookingStart = new DateTime(2025, 12, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            GeneralBookingStart = new DateTime(2025, 12, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            HomeTeamId = new Guid("55555555-5555-5555-5555-555555555555"),
                            League = "Premier League",
                            Round = 19,
                            Season = "2025/2026",
                            StadiumCapacity = 0,
                            StadiumName = "Stamford Bridge"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000004"),
                            Description = "Top-six battle",
                            EventDate = new DateTime(2025, 12, 31, 15, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            Location = "",
                            Title = "Newcastle United vs Aston Villa",
                            Venue = "St James' Park",
                            AwayTeamId = new Guid("88888888-8888-8888-8888-888888888888"),
                            FanPriorityBookingStart = new DateTime(2025, 12, 7, 10, 0, 0, 0, DateTimeKind.Utc),
                            GeneralBookingStart = new DateTime(2025, 12, 11, 10, 0, 0, 0, DateTimeKind.Utc),
                            HomeTeamId = new Guid("77777777-7777-7777-7777-777777777777"),
                            League = "Premier League",
                            Round = 19,
                            Season = "2025/2026",
                            StadiumCapacity = 0,
                            StadiumName = "St James' Park"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000005"),
                            Description = "North London derby",
                            EventDate = new DateTime(2026, 1, 1, 16, 30, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            Location = "",
                            Title = "Arsenal vs Tottenham Hotspur",
                            Venue = "Emirates Stadium",
                            AwayTeamId = new Guid("66666666-6666-6666-6666-666666666666"),
                            FanPriorityBookingStart = new DateTime(2025, 12, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            GeneralBookingStart = new DateTime(2025, 12, 14, 10, 0, 0, 0, DateTimeKind.Utc),
                            HomeTeamId = new Guid("22222222-2222-2222-2222-222222222222"),
                            League = "Premier League",
                            Round = 20,
                            Season = "2025/2026",
                            StadiumCapacity = 0,
                            StadiumName = "Emirates Stadium"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000006"),
                            Description = "London rivalry",
                            EventDate = new DateTime(2026, 1, 2, 18, 30, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            Location = "",
                            Title = "West Ham United vs Chelsea",
                            Venue = "London Stadium",
                            AwayTeamId = new Guid("55555555-5555-5555-5555-555555555555"),
                            FanPriorityBookingStart = new DateTime(2025, 12, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            GeneralBookingStart = new DateTime(2025, 12, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            HomeTeamId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            League = "Premier League",
                            Round = 20,
                            Season = "2025/2026",
                            StadiumCapacity = 0,
                            StadiumName = "London Stadium"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000007"),
                            Description = "Merseyside derby",
                            EventDate = new DateTime(2026, 1, 3, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            Location = "",
                            Title = "Everton vs Liverpool",
                            Venue = "Goodison Park",
                            AwayTeamId = new Guid("33333333-3333-3333-3333-333333333333"),
                            HomeTeamId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            League = "Premier League",
                            Round = 20,
                            Season = "2025/2026",
                            StadiumCapacity = 0,
                            StadiumName = "Goodison Park"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000008"),
                            Description = "Old Trafford showdown",
                            EventDate = new DateTime(2026, 1, 4, 18, 30, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            Location = "",
                            Title = "Manchester United vs Newcastle United",
                            Venue = "Old Trafford",
                            AwayTeamId = new Guid("77777777-7777-7777-7777-777777777777"),
                            FanPriorityBookingStart = new DateTime(2025, 12, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            GeneralBookingStart = new DateTime(2025, 12, 19, 10, 0, 0, 0, DateTimeKind.Utc),
                            HomeTeamId = new Guid("44444444-4444-4444-4444-444444444444"),
                            League = "Premier League",
                            Round = 21,
                            Season = "2025/2026",
                            StadiumCapacity = 0,
                            StadiumName = "Old Trafford"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000009"),
                            Description = "South coast encounter",
                            EventDate = new DateTime(2026, 1, 5, 15, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            Location = "",
                            Title = "Brighton vs Brentford",
                            Venue = "Amex Stadium",
                            AwayTeamId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            FanPriorityBookingStart = new DateTime(2025, 12, 18, 10, 0, 0, 0, DateTimeKind.Utc),
                            GeneralBookingStart = new DateTime(2025, 12, 31, 10, 0, 0, 0, DateTimeKind.Utc),
                            HomeTeamId = new Guid("99999999-9999-9999-9999-999999999999"),
                            League = "Premier League",
                            Round = 21,
                            Season = "2025/2026",
                            StadiumCapacity = 0,
                            StadiumName = "Amex Stadium"
                        });
                });

            modelBuilder.Entity("InTicket.Domain.ConcertTicket", b =>
                {
                    b.HasBaseType("InTicket.Domain.Ticket");

                    b.Property<Guid>("ConcertId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TicketClass")
                        .HasColumnType("int");

                    b.HasIndex("ConcertId");

                    b.ToTable("EventTickets", (string)null);
                });

            modelBuilder.Entity("InTicket.Domain.MatchTicket", b =>
                {
                    b.HasBaseType("InTicket.Domain.Ticket");

                    b.Property<bool>("HomeTeamTicket")
                        .HasColumnType("bit");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TicketClass")
                        .HasColumnType("int");

                    b.HasIndex("MatchId");

                    b.ToTable("MatchTickets", (string)null);
                });

            modelBuilder.Entity("InTicket.Domain.ApplicationUser", b =>
                {
                    b.HasOne("InTicket.Domain.Team", "FavoriteTeam")
                        .WithMany("Fans")
                        .HasForeignKey("FavoriteTeamId");

                    b.Navigation("FavoriteTeam");
                });

            modelBuilder.Entity("InTicket.Domain.Delegation", b =>
                {
                    b.HasOne("InTicket.Domain.ApplicationUser", "Delegate")
                        .WithMany("DelegationsReceived")
                        .HasForeignKey("DelegateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("InTicket.Domain.ApplicationUser", "Delegator")
                        .WithOne("DelegationGiven")
                        .HasForeignKey("InTicket.Domain.Delegation", "DelegatorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Delegate");

                    b.Navigation("Delegator");
                });

            modelBuilder.Entity("InTicket.Domain.Payments", b =>
                {
                    b.HasOne("InTicket.Domain.ApplicationUser", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InTicket.Domain.Ticket", b =>
                {
                    b.HasOne("InTicket.Domain.ApplicationUser", "Holder")
                        .WithMany("Tickets")
                        .HasForeignKey("HolderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Holder");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("InTicket.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("InTicket.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InTicket.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("InTicket.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InTicket.Domain.Match", b =>
                {
                    b.HasOne("InTicket.Domain.Team", "AwayTeam")
                        .WithMany("AwayMatches")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InTicket.Domain.Team", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("InTicket.Domain.ConcertTicket", b =>
                {
                    b.HasOne("InTicket.Domain.Concert", "Concert")
                        .WithMany("ConcertTickets")
                        .HasForeignKey("ConcertId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Concert");
                });

            modelBuilder.Entity("InTicket.Domain.MatchTicket", b =>
                {
                    b.HasOne("InTicket.Domain.Match", "Match")
                        .WithMany("MatchTickets")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("InTicket.Domain.ApplicationUser", b =>
                {
                    b.Navigation("DelegationGiven");

                    b.Navigation("DelegationsReceived");

                    b.Navigation("Payments");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("InTicket.Domain.Team", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("Fans");

                    b.Navigation("HomeMatches");
                });

            modelBuilder.Entity("InTicket.Domain.Concert", b =>
                {
                    b.Navigation("ConcertTickets");
                });

            modelBuilder.Entity("InTicket.Domain.Match", b =>
                {
                    b.Navigation("MatchTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
